---
title: "Project2"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
library(stringr)
library(cowplot)
library(leaflet)
library(scales)
library(knitr)
library(plyr)
library(kableExtra)
```

```{r obj1, echo=TRUE, include=TRUE}
# -- Algorithm --
# 1. Make a function that takes in a data set.
# 2. Select the country name and the case data columns.
# 3. Group by country and sum the rows.
# 4. Select the case data columns.
# 5. Sum each row of the case data.
# 6. Reshape the data & convert dates to objects.
# 7. Call the function for each data set.
# 8. Plot the 3 data frames.

global_confirmed <- read.csv(file="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", stringsAsFactors = FALSE)

global_recoveries <- read.csv(file="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv", stringsAsFactors = FALSE)

global_deaths <- read.csv(file="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", stringsAsFactors = FALSE)

get_total <- function(data_set) {

  data_set %>% # Open the data set
    
    select(Country.Region, X1.22.20:last_col()) %>%  # Select country name and all date cols
    
    group_by(Country.Region) %>%  # Group by country name
    
    summarise_all(sum) %>%  # Total the countries data
    
    select(X1.22.20:last_col()) %>% # Select all date cols
    
    summarise_all(sum) # Total the global data for each date

}

total_confirmed <- get_total(global_confirmed) %>% # get the totals
  
  mutate(Data_Type = "Confirmed") # Adding label column

total_recoveries <- get_total(global_recoveries) %>%
  
  mutate(Data_Type = "Recoveries") # Adding label column

total_deaths <- get_total(global_deaths) %>%
  
  mutate(Data_Type = "Deaths") # Adding label column

global_data <- rbind(total_confirmed, total_recoveries, total_deaths) %>% # Combine the 3 rows
  
  select(Data_Type, X1.22.20:last_col()) %>% # Select labels and data
  
  gather(key=Recorded.Days, value=Cases, X1.22.20:last_col()) %>%  # Reshape data
    
  mutate(Recorded.Days=as.Date(Recorded.Days, format= "X%m.%d.%y")) # Convert dates to objects

ggplot() + # Make the plot
  
  geom_point(global_data, mapping = aes(y=Cases, x=Recorded.Days, color=Data_Type)) + # Point plot
  
  scale_y_continuous(name="Cases", labels=function(x) format(x, scientific = FALSE)) + # y axis
  
  scale_x_date(name="Date") + # x axis
  
  ggtitle("Global Trajectory of Covid-19") +
  
  scale_colour_discrete("Global Data Set")

```

```{r obj2, echo=TRUE, include=TRUE}

global_confirmed <- read.csv(file="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", stringsAsFactors = FALSE)

global_recoveries <- read.csv(file="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv", stringsAsFactors = FALSE)

global_deaths <- read.csv(file="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", stringsAsFactors = FALSE)
 
get_total <- function(data_set) {

  data_set %>% # Open the data set
    
    select(Province.State, Country.Region, Lat, Long, Total.Cases = last_col()) # Select country name and all date cols

}

total_confirmed <- get_total(global_confirmed) %>% # get the totals
  
  mutate(Data_Type = "Confirmed") # Adding label column

total_recoveries <- get_total(global_recoveries) %>%
  
  mutate(Data_Type = "Recoveries") # Adding label column

total_deaths <- get_total(global_deaths) %>%
  
  mutate(Data_Type = "Deaths") # Adding label column

global_data <- rbind(total_confirmed, total_recoveries, total_deaths) %>% # Combine the 3 rows
  
  select(Province.State, Country.Region, Lat, Long, Data_Type, Total.Cases) %>% # Select labels and data

  filter(Total.Cases > 0)

pal <- colorFactor(c("navy", "red", "green"), domain = c("Confirmed", "Recoveries", "Deaths"))

leaflet(global_data) %>% addTiles() %>%
  
  addCircles (
    lat = ~Lat,
    lng = ~Long,
    popup = ~paste(Data_Type, ":", Total.Cases),
    radius = ~Total.Cases,
    color = ~pal(Data_Type),
    label = ~ifelse(Province.State == "", Country.Region, Province.State)
  )

```

```{r obj3, echo=TRUE, include=TRUE}

global_confirmed <- read.csv(file="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", stringsAsFactors = FALSE)

global_recoveries <- read.csv(file="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv", stringsAsFactors = FALSE)

global_deaths <- read.csv(file="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", stringsAsFactors = FALSE)

get_ordered <- function(data_set) {

  data_set %>% # Open the data set
    
    select(Country.Region, Total.Data = last_col()) %>%  # Select country name and all date cols
    
    arrange_at(ncol(.), desc)

}

confirmed_order <- get_ordered(global_confirmed) %>%
  
  mutate(Rank = 1:nrow(global_confirmed))

recovered_ordered <- get_ordered(global_recoveries) %>%
  
  mutate(Rank = 1:nrow(global_recoveries))

deaths_ordered <- get_ordered(global_deaths) %>%
  
  mutate(Rank = 1:nrow(global_deaths))

total_data <- merge(confirmed_order, recovered_ordered, by = "Rank", all = T)
  
total_data <- merge(total_data, deaths_ordered, by = "Rank", all = T)

kable(total_data) %>% 
  
  kable_styling() %>%

  add_header_above(c(" " = 1, "Confirmations" = 2, "Recoveries" = 2, "Deaths" = 2))

```

```{r obj4, echo=TRUE, include=TRUE}

us_confirmed <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", stringsAsFactors = FALSE)

us_deaths <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv", stringsAsFactors = FALSE)

ca_total <- function(data_set) {

  data_set %>% # opening whichever data
      
    select(Province_State, X1.22.20:last_col()) %>% # Select states & data
      
    group_by(Province_State) %>% # Group data by state
      
    summarise_all(sum) %>% # Sum the data
    
    filter(Province_State == "California") # Selecting CA row
  
}

deaths_ca <- ca_total(us_deaths) %>% # Getting CA deaths
  
  mutate(Data_Type = "Deaths") # Adding label column

confirmed_ca <- ca_total(us_confirmed) %>% # Getting CA confirmed cases
  
  mutate(Data_Type = "Confirmed") # Adding label column

total_ca <- rbind(deaths_ca, confirmed_ca) %>% # Combine the 2 rows
  
  select(Data_Type, X1.22.20:last_col()) %>% # Select labels and data
  
  gather(key=Recorded.Days, value=Cases, X1.22.20:last_col()) %>%  # Reshape data
    
  mutate(Recorded.Days=as.Date(Recorded.Days, format= "X%m.%d.%y")) # Convert dates to objects

top3_confirmed_ca <- us_confirmed %>% # Confirmed cases top 3 in CA
  
  select(Admin2, Province_State, X1.22.20:last_col()) %>% # select city, state, data

  filter(Province_State == "California") %>% # Filter CA cities
  
  arrange_at(ncol(.), desc) %>% # Descending order
  
  slice(1:3) %>% # top 3
  
  gather(key=Recorded.Days, value=Cases, X1.22.20:last_col()) %>% # Reshape the data
    
  mutate(Recorded.Days=as.Date(Recorded.Days, format= "X%m.%d.%y")) # Converting to date objects

ggplot() + # Total deaths in California vs confirmed cases
  
  geom_point(total_ca, mapping = aes(y=Cases, x=Recorded.Days, fill=Data_Type, color=Data_Type)) + # Point plot
  
  scale_y_continuous(name="Cases", labels=function(x) format(x, scientific = FALSE)) + # y axis
  
  scale_x_date(name="Date") # x axis

ggplot() + # Top cities in California
  
  geom_point(top3_confirmed_ca, mapping = aes(y=Cases, x=Recorded.Days, fill=Admin2, color=Admin2)) + # Point plot

  scale_y_continuous(name="Cases", labels=function(x) format(x, scientific = FALSE)) + # y axis
  
  scale_x_date(name="Date") # x axis
```

```{r obj5, echo=TRUE, include=TRUE}

us_confirmed <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", stringsAsFactors = FALSE)

us_deaths <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv", stringsAsFactors = FALSE)

cities_cases <- us_confirmed %>%
  
  mutate(Population=us_deaths$Population) %>%

  select(Population, Confirmed_Cases = last_col()-1) 

cities_deaths <- us_deaths %>%
  
  mutate(Confirmed_Cases=cities_cases$Confirmed_Cases) %>%

  select(Confirmed_Cases, Deaths = last_col()-1) %>%
  
  filter(Confirmed_Cases > 10) %>% filter(Deaths > 10)

cities_cases <- cities_cases %>%
  
  filter(Confirmed_Cases > 10) %>% filter(Population > 10)

a <- ggplot(cities_cases, aes(x=Population, y=Confirmed_Cases, color="Blue")) + geom_point() + 
  
  scale_y_continuous("Cases", labels = comma_format(), trans = log2_trans()) + 
  
  scale_x_continuous("Population", labels = comma_format(), trans = log2_trans()) +
  
  theme(legend.position = "none") +
  
  ggtitle("Confirmations vs Population")

b <- ggplot(cities_deaths, aes(x=Confirmed_Cases, y=Deaths)) + geom_point() + 
  
  scale_y_continuous("Deaths", labels = comma_format(), trans = log2_trans()) + 
  
  scale_x_continuous("Cases", labels = comma_format(), trans = log2_trans()) +
  
  ggtitle("Deaths vs Confirmations")

plot_grid(
  a, b,
  align="h"
)

```


